// Generated by scripts/build-scenery.mjs from sources.json. Do not edit by hand.

export type SceneId =
  | 'meadow-dawn'
  | 'wildflower-meadow'
  | 'golden-grass'
  | 'crescent-moon'
  | 'mountain-sunrise'
  | 'moonrise'
  | 'autumn-trail'
  | 'lighthouse'
  | 'wildflower-hillside'
  | 'forest-river'
  | 'canyon-trail'
  | 'lake-sunrise'
  | 'swans'
  | 'golden-trees'
  | 'misty-hayfield'
  | 'snowy-pine'
  | 'snow-sunrise'
  | 'spring-blossoms'
  | 'lake-dock';

export interface SceneCredit {
  title: string;
  creator: string;
  creatorUrl: string;
  license: string;
  licenseUrl: string;
  page: string;
}

export interface Scene {
  id: SceneId;
  /** Available widths in /scenery/<id>-<width>.avif (and .webp) */
  widths: number[];
  /** width / height of the original */
  aspect: number;
  /** A tiny blurred WebP, shown instantly and offline */
  lqip: string;
  /** Average colour, for placeholders and tints */
  color: string;
  /** Darkest and brightest tenth of the blurred image (for the contrast audit) */
  extremes: { dark: string; light: string };
  /** CSS object-position that keeps the subject in frame */
  focus: string;
  description: string;
  credit: SceneCredit;
}

export const SCENES: Record<SceneId, Scene> = {
  "meadow-dawn": {
    "id": "meadow-dawn",
    "widths": [
      640,
      1200,
      1800
    ],
    "aspect": 1.4993,
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoYABAAPtFUo0uoJKMhsAgBABoJQBOkC5hTLh9K4480hnArOAD+r9ktDbZlwKOUm5NVWx9FsqSSm6A2Od9+klSEE7tklI6JYv0n7Bw4CE1O2o9HT3BZh8GLXTVWR+SLJlHIjGecPV+qibVyIfFhjdUDNIICZAw5Q0xgJ1AA",
    "color": "#79646a",
    "extremes": {
      "dark": "#34292d",
      "light": "#cab5af"
    },
    "focus": "45% 55%",
    "description": "Misty meadow at sunrise, Yellowstone",
    "credit": {
      "title": "South Boundary Trail: sunrise near Fox Creek Patrol Cabin",
      "creator": "YellowstoneNPS",
      "creatorUrl": "https://www.flickr.com/photos/80223459@N05",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/80223459@N05/53169845213"
    }
  },
  "wildflower-meadow": {
    "id": "wildflower-meadow",
    "widths": [
      640,
      1200,
      1800
    ],
    "aspect": 1.3333,
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAADwBQCdASoYABIAPtFUoUwoJKMiMBgMAQAaCWIAgjvatjHEAASfFYmBS308BdZanPAuR3swRt3aQAD9404qf8CffseqffINZ1TJkXi1z6CO+DJsbUGO/8A/voQiN+KtPGK6DHXEFrd15ydePQUzgkXrFyklhvE1Vgcl7y5WX8Ej8i7fnDlIkQVz935fYlJLAEorBUMMZa1Y7jq24JU1zFZMsyK5ZkVHkhOhmJkAAAA=",
    "color": "#7f8567",
    "extremes": {
      "dark": "#726543",
      "light": "#83ace0"
    },
    "focus": "50% 60%",
    "description": "Wildflower meadow, Fishlake National Forest",
    "credit": {
      "title": "Yellow Wildflowers on the Fishlake",
      "creator": "Fishlake National Forest Photography",
      "creatorUrl": "https://www.flickr.com/photos/195764176@N02",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/195764176@N02/52320437219"
    }
  },
  "golden-grass": {
    "id": "golden-grass",
    "widths": [
      640,
      1200,
      1800
    ],
    "aspect": 1.6164,
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAAAwBQCdASoYAA8APtFUo0uoJKMhsAgBABoJZgCdMoMYPYEbut/9igAxxijOSenWgCq4aAD3jghJcXXzedD8Y72519rb8AespzAfaEgH5MF980MJeldm9cv8sWB+xRdTvBozt2c7LWF/GtnSn1B3EbSparWck31FqlU5OhuXw86wvDYqVqOmqP0P7mPX50bZCvF177ysbtRP4Z7GbN0yg0wRQRTGdSe0XBqdXfKc+AAAAA==",
    "color": "#59554c",
    "extremes": {
      "dark": "#222b35",
      "light": "#7290a6"
    },
    "focus": "58% 55%",
    "description": "Golden grass below the mountains",
    "credit": {
      "title": "Fox Glacier. Westland National Park.NZ",
      "creator": "Bernard Spragg",
      "creatorUrl": "https://www.flickr.com/photos/88123769@N02",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page": "https://www.flickr.com/photos/88123769@N02/12643854623"
    }
  },
  "crescent-moon": {
    "id": "crescent-moon",
    "widths": [
      640,
      1200,
      1800
    ],
    "aspect": 1.5004,
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoYABAAPtFUpEuoJKOhsAgBABoJYwCdACHXZddpcW+/gCAA/u9eqjF11dhB8jEiDQE4bfHegdOWc7AGgc9sJ96q5BrxoMexz/Frid70O1HRjXine2uZVvtj8Pad2lei4AA=",
    "color": "#2a3332",
    "extremes": {
      "dark": "#090807",
      "light": "#515850"
    },
    "focus": "26% 26%",
    "description": "Crescent moon over a quiet ridge",
    "credit": {
      "title": "Starry Sky",
      "creator": "San Bernardino Nat'l Forest",
      "creatorUrl": "https://www.flickr.com/photos/135365655@N07",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/135365655@N07/24874313131"
    }
  },
  "mountain-sunrise": {
    "id": "mountain-sunrise",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.4352,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBQCdASoYABEAPtFWpk2oJCOiMBgIAQAaCUATplAALfvyhjKykesAhkChn1rba0JwAPnHDonFPwfgirHQGilqyPqgbk3VQcqxBgRJbWvp3nbZtoPygloYj6dMMGU3/ePx/DjH6IrN/UUr/fHPDid1TvZ044tDEAatMHTdBzpl8fbtnYbfAOcpmGCuzEBrAU6WcpZsUn88svHOgTIAAA==",
    "color": "#756149",
    "extremes": {
      "dark": "#221f1b",
      "light": "#caa070"
    },
    "focus": "34% 40%",
    "description": "Sunrise on Aoraki / Mount Cook",
    "credit": {
      "title": "Sunrise Mount Cook",
      "creator": "Bernard Spragg",
      "creatorUrl": "https://www.flickr.com/photos/88123769@N02",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page": "https://www.flickr.com/photos/88123769@N02/9411931749"
    }
  },
  "moonrise": {
    "id": "moonrise",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.4996,
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoYABAAPtFUpEuoJKOhsAgBABoJQBOgAlQC/Y7D8ab0igAA+Zw8n1Abqq790PrgYVsBXfwcoDVh+Jr85Ch6L7jUEpNsdQS/jtMkugYvAAA=",
    "color": "#575f78",
    "extremes": {
      "dark": "#3d3636",
      "light": "#6c81a8"
    },
    "focus": "50% 55%",
    "description": "October moonrise",
    "credit": {
      "title": "October Moonrise",
      "creator": "USFWS Mountain Prairie",
      "creatorUrl": "https://www.flickr.com/photos/51986662@N05",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/51986662@N05/52581596461"
    }
  },
  "autumn-trail": {
    "id": "autumn-trail",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.7747,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADQAwCdASoYAA4APtFWpEuoJKOhsAgBABoJagCdMoABO5TwYyIEQEAA/HUGSFM+WzZNjo4KBPxSot0Wv6E1/JZAbJzgV0SZlta/IAYqKZr7G1rjtwGZ2C2npQAMdDGTHHQgMCjBNCyA2u8FNES0PflaW3ZIOnjBTed/rcz3MF192ADdCtyOfEv0Rsa2ezBkouW6Ac53j8NQNObxzwAAAA==",
    "color": "#967d55",
    "extremes": {
      "dark": "#7c6540",
      "light": "#b09b5e"
    },
    "focus": "52% 60%",
    "description": "An autumn trail through aspens",
    "credit": {
      "title": "An autumn trail.",
      "creator": "Bernard Spragg",
      "creatorUrl": "https://www.flickr.com/photos/88123769@N02",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/88123769@N02/52468554191"
    }
  },
  "lighthouse": {
    "id": "lighthouse",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.5092,
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoYABAAPtFUpEuoJKOhsAgBABoJbACdMoADTF5OZ7eSms94d2AA/sM8h1dZTXhFYGzXowZoxiyhxF3oMpUjUdzt+hWS2V80u3jNC2mRM9JykUx42lNEA2FLxR0y9hID48UajItBf66QB3j6Sj2w4AAA",
    "color": "#ae815a",
    "extremes": {
      "dark": "#595552",
      "light": "#e6ad6a"
    },
    "focus": "72% 52%",
    "description": "Delaware Breakwater Lighthouse at dusk",
    "credit": {
      "title": "Delaware Breakwater Lighthouse",
      "creator": "Land Matters Photography",
      "creatorUrl": "https://www.flickr.com/photos/44643798@N05",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page": "https://www.flickr.com/photos/44643798@N05/15189086153"
    }
  },
  "wildflower-hillside": {
    "id": "wildflower-hillside",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.4982,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwAwCdASoYABAAPtFUo0uoJKMhsAgBABoJYgCdACFpdykBuuYnElV4AP5kadyRS5BDzNvLzPL7SZoXUNeCfdQ4bfsU4U/vCHen1Gb/TMRQisPmZX04wJPq/TaPpjjEiz3QTJh/bh8m/gsn2pTw7OvZV/4kbh5A5OQa/DTt2b6hrYr33OOBVWax9Nwxh3aOIkTNDYAA",
    "color": "#6c7060",
    "extremes": {
      "dark": "#3b3b1f",
      "light": "#c8ccd4"
    },
    "focus": "50% 62%",
    "description": "Summer wildflowers below the San Francisco Peaks",
    "credit": {
      "title": "Summer Wildflowers east of the Peaks",
      "creator": "Coconino NF Photography",
      "creatorUrl": "https://www.flickr.com/photos/42034606@N05",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page": "https://www.flickr.com/photos/42034606@N05/36050457043"
    }
  },
  "forest-river": {
    "id": "forest-river",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.5004,
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBACdASoYABAAPtFUo0uoJKMhsAgBABoJagCdMoRwABvWdmiH15IYAAD+0HBUjlq8cIfCC3mkRSrW0gG0Z/dGFb8xWygg7FitSVq5P7TGwpmTf7vGHghJJyWmct2Psfy5F7n6au1KhZrlxfVegu/hfkAGJSokLMl6q3UgsshR84Aai3ALljB8RX6+3adg+D//PlXrak3wIaw97QAAAA==",
    "color": "#6c5928",
    "extremes": {
      "dark": "#48451c",
      "light": "#7e733a"
    },
    "focus": "50% 55%",
    "description": "A river through an autumn forest",
    "credit": {
      "title": "Fall color McKenzie River, Oregon",
      "creator": "Bonnie Moreland (free images)",
      "creatorUrl": "https://www.flickr.com/photos/66741228@N05",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/66741228@N05/43346987640"
    }
  },
  "canyon-trail": {
    "id": "canyon-trail",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.4982,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoYABAAPtFUo0uoJKMhsAgBABoJQBadtQA09Jgyq0kuP/VCEPqwAP7hp48vw96EoLdseZaPUPAwqRQGpdGPufbMzG+W6++UY1Sa4x/Egn9Ais00Nd5jBxFxCRz4IWRuARZLo8XL9Mgou4o3j41fKru7iwb4iRVXTxPZbxVShS7liVhJRuTG8Z9LDtc/GjPiwAA=",
    "color": "#867c70",
    "extremes": {
      "dark": "#403f2e",
      "light": "#b9b5bb"
    },
    "focus": "45% 60%",
    "description": "Bell Trail, Coconino National Forest",
    "credit": {
      "title": "Bell Trail",
      "creator": "Coconino NF Photography",
      "creatorUrl": "https://www.flickr.com/photos/42034606@N05",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page": "https://www.flickr.com/photos/42034606@N05/38152956565"
    }
  },
  "lake-sunrise": {
    "id": "lake-sunrise",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.5004,
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBACdASoYABAAPtFUo0uoJKMhsAgBABoJZQBUQx38MXZ3Bt71rs4cKAAA8bbXuVF9f08Q1s/6UOgn7g9JkHy1LRhiaVABirgnqDLFyOKXc4Bs+ldZ2gHLZK9V5/TuHanRsfh7FRqcmYXjJdlYuYaPXIBQZLSWEbUYoB44DovR2QAA",
    "color": "#67626f",
    "extremes": {
      "dark": "#2d2a32",
      "light": "#aea4b1"
    },
    "focus": "50% 50%",
    "description": "Sunrise at Sparks Lake, Oregon",
    "credit": {
      "title": "Sunrise at Sparks Lake, Oregon .",
      "creator": "Bonnie Moreland (free images)",
      "creatorUrl": "https://www.flickr.com/photos/66741228@N05",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/66741228@N05/48025381053"
    }
  },
  "swans": {
    "id": "swans",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.3351,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACQBACdASoYABIAPtFYpk0oJKOosBgIARAaCWMAxNgGfFsF+2rlZDy+ASD11gAA/TmyHcdJYoDgvHsL1acRqUKXbH0LVFvA1FGQ8pZw1Dq4zppwuhJyY8YFcDn/ASOj5p0L9pyFbbxj4t6Q2/H7bFYQJSyx/qDjshxIJ4QitQWFu+AAAAA=",
    "color": "#818574",
    "extremes": {
      "dark": "#717345",
      "light": "#a0a2a6"
    },
    "focus": "45% 60%",
    "description": "Trumpeter swans, Seedskadee National Wildlife Refuge",
    "credit": {
      "title": "Trumpeter swans at Seedskadee National Wildlife Refuge",
      "creator": "USFWS Mountain Prairie",
      "creatorUrl": "https://www.flickr.com/photos/51986662@N05",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/51986662@N05/52250350141"
    }
  },
  "golden-trees": {
    "id": "golden-trees",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.5004,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoYABAAPtFUo0uoJKMhsAgBABoJbACdABX+Iyvup0xUsAZAAAD+vZecYAyiHixWlQJYXL7Vfes+HnfEqL6WbdGbYTRXfzFJfAQ16D+uO7M2f2rlRkb43hGPRDBQB7sQL3fCcuDq/cCVP9RXWwi8q8hJscsdRRgDRB04zYZiY/LdjDrKYAQAAA==",
    "color": "#88724e",
    "extremes": {
      "dark": "#534015",
      "light": "#cbc8c0"
    },
    "focus": "40% 50%",
    "description": "Golden trees in autumn",
    "credit": {
      "title": "Follow the yellow leaf road.",
      "creator": "Bonnie Moreland (free images)",
      "creatorUrl": "https://www.flickr.com/photos/66741228@N05",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/66741228@N05/48944622288"
    }
  },
  "misty-hayfield": {
    "id": "misty-hayfield",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.5015,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBACdASoYABAAPtFWpEuoJKOhsAgBABoJYwC7H8G6zAcZgXumtf9i+AAA/vNwOd6FKg3cb88Ruw92JRBW0VV4NxSO/LufqyaUKdGup5m8V2i6ZyBDGsPpI+gPpUaXs1BhgpadtdL64M5YypAlxMdFAQhRN51yz05bfqzTupxrkvXcXAA=",
    "color": "#8e8681",
    "extremes": {
      "dark": "#464331",
      "light": "#f0efec"
    },
    "focus": "50% 60%",
    "description": "A misty hayfield at first light",
    "credit": {
      "title": "Foggy grasslands",
      "creator": "U. S. Fish and Wildlife Service - Northeast Region",
      "creatorUrl": "https://www.flickr.com/photos/43322816@N08",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/43322816@N08/9816823626"
    }
  },
  "snowy-pine": {
    "id": "snowy-pine",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.3887,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwBACdASoYABEAPtFgqE+oJSOiKAgBABoJYwCdMyGBZS5p0Qzn6ZALRc6ABKsccwAA/rtr9bBvAFzmR6t/x/0XJ2kJqMGyEVhpzYIbSsWxnJzCilvsZuGWUkh5fngpxczKKDhvcR0GN4yvaLdJIga8GG7bnMcbbFChJlaijFPsk70eqgmj+NBCYVFZbY210BbWoAAA",
    "color": "#5c778e",
    "extremes": {
      "dark": "#2c3a42",
      "light": "#9fc8ea"
    },
    "focus": "45% 45%",
    "description": "Fresh snow and a crescent moon, Kaibab National Forest",
    "credit": {
      "title": "Oak Hill Snow Play 2019",
      "creator": "Kaibab National Forest Photography",
      "creatorUrl": "https://www.flickr.com/photos/48448783@N06",
      "license": "CC BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "page": "https://www.flickr.com/photos/48448783@N06/49180632948"
    }
  },
  "snow-sunrise": {
    "id": "snow-sunrise",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.4993,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACQBACdASoYABAAPtFUo0uoJKMhsAgBABoJQBOmUGMEz/gLXGiRoAvDKih+GYAA3lyecg/Zp1biscNZT5e8g27xyC/AYgZNOxlN3zaOc2vc+pJyJ4pvmOu/WXtQ4qgMibmP2KEWelzEdnzwjdB9Xb9SIVVbO/tRWaVPQPsqVJcbfsbAAAA=",
    "color": "#8c7e73",
    "extremes": {
      "dark": "#676360",
      "light": "#b49678"
    },
    "focus": "50% 40%",
    "description": "Fresh snow at sunrise on Sheep Mountain, Yellowstone",
    "credit": {
      "title": "Fresh snow sunrise on Sheep Mountain",
      "creator": "YellowstoneNPS",
      "creatorUrl": "https://www.flickr.com/photos/80223459@N05",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/80223459@N05/54964006671"
    }
  },
  "spring-blossoms": {
    "id": "spring-blossoms",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.4085,
    "lqip": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAABwBQCdASoYABEAPtFcqE4oJSQiKAqpABoJZACxHxglsQt6Lhlan0QQg8MOixe5Vb2LAitgAOFOfnTQ2U8XsaeysSJCBkq5A+IxuxKAXnQ+I7Tx2IMU2LoVq5eVb+VBteK0dyFmCmf63fhMoo9iSrnnND8hfu7ZWz2YjJhQPrxcQCBa5z4089qqKjt9Fl5rnCA1isw6YJqhseRiMn8+skgax4SwYr/PtSE0ZVoxjACXcqGLNu2e8tJKw/I6Dg3bEsZwqiBUB6hAAaSAAAA=",
    "color": "#87774d",
    "extremes": {
      "dark": "#464737",
      "light": "#b6954c"
    },
    "focus": "55% 50%",
    "description": "Spring blossoms",
    "credit": {
      "title": "Ricoh TLS 401 with Helios 44-2 - Spring Blossoms",
      "creator": "Kojotisko",
      "creatorUrl": "https://www.flickr.com/photos/98796230@N03",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page": "https://www.flickr.com/photos/98796230@N03/25689448843"
    }
  },
  "lake-dock": {
    "id": "lake-dock",
    "widths": [
      480,
      800,
      1200
    ],
    "aspect": 1.5004,
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBACdASoYABAAPtFYpEuoJSOhsAgBABoJZQCdMoMrZEmf1ZXLDpZ/8/QAAMsmv1p0CUnYe4TRL3EIFAnAeYew10c8tXxdwp1rOgjYiW1EopPxO95PEcwWFBWpuM626nbftz99zQqowcXrJUg+m9YB2z/XFmLfRQqa6vdQH+u0lNAVkEMXrR9gGd50EX0qRhtEj7ipcYAAAA==",
    "color": "#999495",
    "extremes": {
      "dark": "#5d595c",
      "light": "#d1c8c0"
    },
    "focus": "62% 55%",
    "description": "Lake McDonald at sunrise, Glacier National Park",
    "credit": {
      "title": "Lake McDonald Public Dock Sunrise 3.19.16 (2)",
      "creator": "GlacierNPS",
      "creatorUrl": "https://www.flickr.com/photos/43288043@N04",
      "license": "Public Domain Mark 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
      "page": "https://www.flickr.com/photos/43288043@N04/26288117396"
    }
  }
};
