import {
  Anchor,
  Backpack,
  BabyCarriage,
  BookOpen,
  Briefcase,
  Butterfly,
  Cake,
  ChalkboardTeacher,
  CloudSun,
  Compass,
  DoorOpen,
  Drop,
  Exam,
  Eye,
  Feather,
  Fingerprint,
  Flag,
  Flower,
  FlowerTulip,
  HandHeart,
  Handshake,
  Heart,
  HeartBreak,
  Heartbeat,
  HeartStraight,
  Hourglass,
  HouseLine,
  Key,
  Leaf,
  Lighthouse,
  MapTrifold,
  Moon,
  MoonStars,
  Mountains,
  Notebook,
  Path,
  PersonSimpleRun,
  Plant,
  Shield,
  ShieldCheck,
  Signpost,
  Sparkle,
  Star,
  StarFour,
  SuitcaseRolling,
  Sun,
  SunHorizon,
  Target,
  Tree,
  TreeEvergreen,
  Users,
  UsersThree,
  Waves,
  Wind,
  type Icon,
  type IconWeight,
} from '@phosphor-icons/react';

const ICONS: Record<string, Icon> = {
  Anchor, Backpack, BabyCarriage, BookOpen, Briefcase, Butterfly, Cake, ChalkboardTeacher, CloudSun, Compass,
  DoorOpen, Drop, Exam, Eye, Feather, Fingerprint, Flag, Flower, FlowerTulip, HandHeart, Handshake, Heart,
  HeartBreak, Heartbeat, HeartStraight, Hourglass, HouseLine, Key, Leaf, Lighthouse, MapTrifold, Moon, MoonStars,
  Mountains, Notebook, Path, PersonSimpleRun, Plant, Shield, ShieldCheck, Signpost, Sparkle, Star, StarFour,
  SuitcaseRolling, Sun, SunHorizon, Target, Tree, TreeEvergreen, Users, UsersThree, Waves, Wind,
};

/** Resolves the icon names used in content (taxonomy, occasions, journeys) to Phosphor icons. */
export function TopicIcon({ name, size = 22, weight = 'duotone', className }: { name: string; size?: number; weight?: IconWeight; className?: string }) {
  const Component = ICONS[name] ?? Sparkle;
  return <Component size={size} weight={weight} className={className} aria-hidden="true" />;
}
